### PR TITLE
chore: Update README, remove old KC/GH related conf

### PR DESCRIPTION
**Pull request by tplevko**
There were some outdated template confs in the README. Removed also unused KC related fields from templates.
Also updated the rest host name in syndesis-ci template I added. It caused conflicts with the UI host name, had to change it.

### CODE REVIEW

**Review by jimmidyson — DISMISSED** [review]

**Comment by dsimansk** [comment]
retest this please

**Comment by zregvart** [comment]
Judging by the [console output](https://jenkins-syndesis-ci.b6ff.rh-idev.openshiftapps.com/job/syndesis-templates/job/PR-151/3/console) of the build, the CI fails because of a f8 client vs k8s server version mismatch. I think that might be an issue with our Jenkins plugin version?

Perhaps we should manually merge this?

//cc @iocanel, @rhuss

**Comment by dsimansk** [comment]
@zregvart that is related to API groups of OpenShift 3.6 and the f8 client version. Afaik the same that forced version fiddling in syndesis-rest.

And I'm backing up the merge manually approach :)

**Review by jimmidyson — APPROVED** [review]

**Comment by jimmidyson** [comment]
Yep let's manually merge this but we do need to sort out that mismatch client version.

**Pull request merged**
