### PR TITLE
fix: Fix dodgy oauth proxy image names

### LINKED ISSUE #124: Error converting YAML to JSON - oc create using syndesis templates
Following the instructions in the Quickstart, any attempt to use "_oc create -f https://raw.githubusercontent.com/syndesisio/syndesis-openshift-templates/master/syndesis-dev-restricted.yml_" or alternative templates result in this error --
**error: error converting YAML to JSON: yaml: line 120: mapping values are not allowed in this context**

I have attempted to create templates using either developer or system:admin accounts. Has something changed in the templates?

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #124

### CODE REVIEW

**Comment by jimmidyson** [comment]
Tests are failing because test cluster (`rh-idev`) doesn't support [re-encrypted routes](https://docs.openshift.com/container-platform/3.6/architecture/networking/routes.html#re-encryption-termination) using [service serving certificates](https://docs.openshift.com/container-platform/3.6/dev_guide/secrets.html#service-serving-certificate-secrets) due to the version of OpenShift deployed (3.5 in staging vs 3.6 in prod):

`error: Route "syndesis-rest" is invalid: spec.tls.destinationCACertificate: Required value`

This is an enhancement that I could drop back to edge termination but really do like the effectively end-to-end encryption that re-encrypted routes provide. I hate to drop back to work around previous versions of openshift when our target prod platform gives us the capabilities we want.

Thoughts @rhuss @zregvart @dsimansk?

**Review by rhuss — APPROVED** [review]
💇‍♂️

**Comment by rhuss** [comment]
@jimmidyson I agree that making compromises only because of our weird dev setup is not nice. I would however still go for a common solution, since I think it's _still_ secure (although not *that* secure). We should raise an issue as reminder, that when we resolved the situation with 3.5 dev vs. 3.6 prod we go back to the renecrypt strategy.

**Comment by rhuss** [comment]
BTW, i would be cool if we collect somewhere all the issues we had with the discrepancy of prod vs dev cluster (just to have some datapoints for arguments)

So far I remember:

* re-encrypted routes
* subPath mounting (or was this an issue on 3.6, too ?)
* initContainers as annotations

**Comment by dsimansk** [comment]
* ImageChange triggers

**Comment by jimmidyson** [comment]
Switched back to edge encryption.

Jenkins is dead so no PR testing...

**Pull request merged**
