### PR TITLE
ENTESB-6993 Change 

### PR DESCRIPTION
**Pull request by jonathanchristison**
Changed mount location of the config file to the nginx src rootdir (/opt/app-root/src)

### CODE REVIEW

**Comment by jonathanchristison** [comment]
See PR https://github.com/syndesisio/syndesis-ui/pull/1020

**Comment by KurtStam** [comment]
@jonathanchristison can you do a rebase please?

**Comment by rhuss** [comment]
We need to run the generator, too. @jonathanchristison if this is no possible for you (it's about running generator/run.sh) then I can do it and push to this branch.

**Comment by rhuss** [comment]
Please note that this PR can only be merged when https://github.com/syndesisio/syndesis-ui/pull/1020 is merged.

**Comment by jonathanchristison** [comment]
Superseded by #110

**Pull request closed without merging**
