### PR TITLE
Adding templates for the todo-app

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by chirino** [comment]
@KurtStam hey. Any idea why the db auth is not right?

**Comment by KurtStam** [comment]
@chirino looks ok to me looking at the template. You can use psql from within the todo pod to debug it iff needed. Can you try: psql -U sampledb -d sampledb -h synthesis-db

**Comment by KurtStam** [comment]
I fixed setting the password in the second commit of https://github.com/syndesisio/syndesis-openshift-templates/pull/113. With that all works great.

**Comment by KurtStam** [comment]
LGTM

**Pull request merged**
