### PR TITLE
Remove the -Djavax.net.ssl.trustStore=/tls-keystore/openshift-truststore.jks arg.

### PR DESCRIPTION
**Pull request by chirino**
That file does not exist anymore in the image.

### CODE REVIEW

**Comment by chirino** [comment]
Was running into this error when creating new Twitter connections:
https://gist.github.com/chirino/a37a34a71ad297c647f58668dc7ba43e

**Review by rhuss — COMMENTED** [review]
LGTM as this deployment doesn't use the pemtokeystore init container anymore (we dont have to access keycloak anymore). But I'd like to confirm @jimmidyson that this is true.

**Review by jimmidyson — APPROVED** [review]
yep, sorry for missing this

**Comment by chirino** [comment]
Jenkins is down at the moment.. time for manual merge.

**Pull request merged**
