### PR TITLE
Add PostgreSQL template parameters

### PR DESCRIPTION
**Pull request by jimmidyson**
@rhuss This is complimentary to the minishift PR. Would like consistency if it makes sense to so perhaps we use the same parameters in here in minishift template? Perhaps without PV size though.

### CODE REVIEW

**Comment by rhuss** [comment]
No problem, I can take the parameters over to #15

**Comment by rhuss** [comment]
@jimmidyson btw, currently for Minishift an `emptyDir` volume is used (as in the template). Wouldn't it make sense to change this to a `hostPath` volume so that the data survives restarts ?

**Comment by jimmidyson** [comment]
hostPath volumes only work if pods running as root (design decision upstream) so not really. I know in recent/next version of minishift PVs will be provided. In fact, I'm pretty sure they already are with 1.0 beta releases?

**Comment by rhuss** [comment]
just got from the README that its not supported, but it seems to work.

wdyt about adding a hostPath PV directly in the template for minishift ? as its for development purpose anyway on a local node, shouldn't harm.

**Comment by jimmidyson** [comment]
You could have a host path volume, yes. That directory would need to exist and be world writable (well probably 770 would do) otherwise arbitrary uids won't be able to write to it.

**Comment by rhuss** [comment]
What's about something below /tmp ? or maybe even /tmp ? Have no much influence on the node container anyway. Except maybe with an init-container but I guess this container is not running as root as well.

Let me try that later.

**Comment by jimmidyson** [comment]
It explicity sets permissions IIRC but worth a try.

**Comment by jimmidyson** [comment]
Are you happy with merging this though @rhuss?

**Comment by rhuss** [comment]
yes, I will rebase my proposal on this later.

**Pull request merged**
