### PR TITLE
feat: Make github parameters optional by defaulting to dummy values

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by iocanel** [comment]
What is the motivation?

**Comment by jimmidyson** [comment]
from the commit message:

The github parameters will be updated on first time use of Syndesis. These dummy values allow for
them to be overridden at deploy time, if the user already has these values, useful for testing and
repeatable deployments, while allowing for runtime configuration if they are not provided.

**Comment by jimmidyson** [comment]
This is part of the work to get first time user experience that walks the user through the process of creating a github app and configuring syndesis when the first user hits the app

**Comment by iocanel** [comment]
Thanks!

**Review by iocanel — APPROVED** [review]
LGTM

**Pull request merged**
