### PR TITLE
Adding a go based deployment generator. The template still needs some work.

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by iocanel** [comment]
Assuming that we do need to keep the `*-dev` templates around, they do have some structural differences, which we might need to handle.

**Comment by chirino** [comment]
Yeah.. should be doable easily since this thing is using mustache templates https://mustache.github.io/mustache.5.html

**Comment by jimmidyson** [comment]
I'm not sure what problem this is trying to solve? Looks like you're creating a poor man's oc process...

**Comment by chirino** [comment]
@jimmidyson  yeah.. it kinda still a thought.  main purpose is figuring out a way to avoid needing to define so many templates.  Main main question right now is should we be generating templates which laters get applied by openshift, or should we be applying templates which immediately create ocp resources kinda like templates.

BTW since it's based on a mustache template, I find it's less poor than a ocp template since it can have conditionals and loops in it.

**Comment by iocanel** [comment]
@chirino, @jimmidyson : While I am 100% on board that we need some kind of tooling to generate our templates, I am don't think that we need `yet another generator from templates`. Mostly, because templates themselves are ... Templates.

If you take a look at the existing templates, you'll see that the difference is not in values. But in structure and they are also cross-cutting:

- `globaly replace imagestreams with docker images`
- `globaly disable pvc`
- `multi vs single tenant`

and so on. 

So, I am thinking that maybe what we need is to make use of the `visitor` support which is already present in our model classes and just implement a visitor for each of those features. Then we can just hack a tool, that would allow us to combine visitors and generate all the resources. 

Just a thought.

**Comment by iocanel** [comment]
In other words, I am suggesting that we implement in java something similar to `fish-pepper` (multidimensional generator) but that would use visitors instead of templates.

**Comment by rhuss** [comment]
@chirino what is the status of this PR as you already [directly pushed](https://github.com/redhat-ipaas/openshift-templates/commit/3660a76f7d4dec9b163ceb3c190725a1cb26d273) the template generator to upstream master ? Can this PR then be closed then as this is the final word now ?

Would love to know the answer as I wanna continue to add the ipaas-verifier into the other templates and would like to know how to continue. This is blocking me currently.

**Comment by chirino** [comment]
Yep.. closing.. the template generator works more like fish-pepper as iocanel requested.

**Comment by rhuss** [comment]
@chirino thanks. btw I consider it good style to not push to master directly except for trivial updates (like fixing typos in the README or testing circleci.yml). 

Anything other confuses and irritates people (including myself).

**Pull request closed without merging**
